// Types for menu
export const SET_CURRENT_MENU = 'SET_CURRENT_MENU';
export const RESET_CURRENT_MENU = 'RESET_CURRENT_MENU';
export const MAKE_TOP_MENU_CURRENT = 'MAKE_TOP_MENU_CURRENT';
export const RESTORE_TOP_MENU = 'RESTORE_TOP_MENU';

// Types for modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// Types for order
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CHANGE_ITEM = 'UPDATE_ITEM';
export const COPY_ITEM = 'COPY_ITEM';
export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
export const SEND_ORDER = 'SEND_ORDER';
export const PRINT_ORDER = 'PRINT_ORDER';
export const ADD_MODIFIER = 'ADD_MODIFIER';
export const CHANGE_MODIFIER = 'CHANGE_MODIFIER';
export const REMOVE_MODIFIER = 'REMOVE_MODIFIER';

// Types for scratchPad
export const ADD_ITEM_TO_SCRATCH = 'ADD_ITEM_TO_SCRATCH';
export const REMOVE_ITEM_FROM_SCRATCH = 'REMOVE_ITEM_FROM_SCRATCH';
export const TOGGLE_ITEM_IN_SCRATCH = 'TOGGLE_ITEM_IN_SCRATCH';
export const SET_ITEM_SIZE = 'SET_ITEM_SIZE';
export const SET_HALF_ORDERING = 'SET_HALF_ORDERING';
export const RESET_SCRATCH = 'RESET_SCRATCH';
export const SET_SIZE_REQUIRED = 'SET_SIZE_REQUIRED';

// Types for qualifiers
export const INIT_QUALIFIERS = 'INIT_QUALIFIERS';
export const SET_EXTRA = 'SET_EXTRA';
export const SET_LITE = 'SET_LITE';
export const SET_SIDE = 'SET_SIDE';
export const SET_H1 = 'SET_H1';
export const SET_H2 = 'SET_H2';
export const SET_WHOLE = 'SET_WHOLE';
export const SET_QUALIFIER = 'SET_QUALIFIER';

// Types for clock
export const SET_TIME = 'SET_TIME';

// Types for app
export const SET_NEXT_CHOICE = 'SET_NEXT_CHOICE';
export const CANCEL_CHOICES = 'CANCEL_CHOICES';

export default {
  SET_CURRENT_MENU,
  RESET_CURRENT_MENU,
  MAKE_TOP_MENU_CURRENT,
  RESTORE_TOP_MENU,
  SHOW_MODAL,
  HIDE_MODAL,
  ADD_ITEM,
  REMOVE_ITEM,
  COPY_ITEM,
  CHANGE_ITEM,
  SET_SELECTED_ITEM,
  SEND_ORDER,
  PRINT_ORDER,
  ADD_MODIFIER,
  CHANGE_MODIFIER,
  REMOVE_MODIFIER,
  ADD_ITEM_TO_SCRATCH,
  REMOVE_ITEM_FROM_SCRATCH,
  TOGGLE_ITEM_IN_SCRATCH,
  SET_ITEM_SIZE,
  SET_SIZE_REQUIRED,
  SET_HALF_ORDERING,
  RESET_SCRATCH,
  INIT_QUALIFIERS,
  SET_EXTRA,
  SET_LITE,
  SET_SIDE,
  SET_H1,
  SET_H2,
  SET_WHOLE,
  SET_QUALIFIER,
  SET_TIME,
  SET_NEXT_CHOICE,
  CANCEL_CHOICES
};