// Types for menu
export const SET_CURRENT_MENU = 'SET_CURRENT_MENU';
export const RESET_CURRENT_MENU = 'RESET_CURRENT_MENU';
export const MAKE_TOP_MENU_CURRENT = 'MAKE_TOP_MENU_CURRENT';
export const RESTORE_TOP_MENU = 'RESTORE_TOP_MENU';

// Types for order
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CHANGE_ITEM = 'UPDATE_ITEM';
export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
export const SEND_ORDER = 'SEND_ORDER';
export const PRINT_ORDER = 'PRINT_ORDER';
export const ADD_MODIFIER = 'ADD_MODIFIER';
export const REMOVE_MODIFIER = 'REMOVE_MODIFIER';

// Types for scratchPad
export const ADD_ITEM_TO_SCRATCH = 'ADD_ITEM_TO_SCRATCH';
export const REMOVE_ITEM_FROM_SCRATCH = 'REMOVE_ITEM_FROM_SCRATCH';
export const TOGGLE_ITEM_IN_SCRATCH = 'TOGGLE_ITEM_IN_SCRATCH';
export const SET_ITEM_SIZE = 'SET_ITEM_SIZE';
export const SET_HALF_ORDERING = 'SET_HALF_ORDERING';
export const RESET_SCRATCH = 'RESET_SCRATCH';
export const SET_SIZE_REQUIRED = 'SET_SIZE_REQUIRED';

export default {
  SET_CURRENT_MENU,
  RESET_CURRENT_MENU,
  MAKE_TOP_MENU_CURRENT,
  RESTORE_TOP_MENU,
  ADD_ITEM,
  REMOVE_ITEM,
  CHANGE_ITEM,
  SET_SELECTED_ITEM,
  SEND_ORDER,
  PRINT_ORDER,
  ADD_MODIFIER,
  REMOVE_MODIFIER,
  ADD_ITEM_TO_SCRATCH,
  REMOVE_ITEM_FROM_SCRATCH,
  TOGGLE_ITEM_IN_SCRATCH,
  SET_ITEM_SIZE,
  SET_SIZE_REQUIRED,
  SET_HALF_ORDERING,
  RESET_SCRATCH
};